# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        
      - run: |
          echo "Hello world from ${{ github.actor }}."
          echo "Current branch is '${{ github.ref }}' in Environment: ${{ vars.ENVIRONMENT }}  ."
          echo "Hello ${{ secrets.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
          echo "My 1st secret is 🤫 ${{ secrets.MY_SECRET_01 }}."
          echo "My 2nd secret is 🤫 ${{ secrets.MY_SECRET_02 }}."
          echo "Current branch is '${{ github.ref }}'."          

      - run: tree
